<?php

namespace App\Nova;

use App\Models\AdminUser;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Email;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Password;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Fields\Text;

class AdminsResource extends Resource
{
    public static $model = AdminUser::class;

    public static $title = 'name';

    public static $search = [
        'id', 'name', 'email'
    ];


    public static function label()
    {
        return "Администраторы"; // TODO: Change the autogenerated stub
    }

    public function fields(Request $request): array
    {
        return [
            ID::make()->sortable(),

            Text::make('Имя пользователя','name')->sortable()->rules('required'),

            Email::make('E-mail','email')->sortable()->rules('required', 'email', 'max:254'),

            Password::make('Пароль','password')
                ->onlyOnForms()
                 ->creationRules('required', 'string', 'min:8')
                ->updateRules('nullable', 'string', 'min:8'),

            Select::make('Статус пользователя', 'status')->options([
                'active' => 'Активен',
                'ban' => 'Забанен',
            ])->default('active'),
        ];
    }

    public function cards(Request $request): array
    {
        return [];
    }

    public function filters(Request $request): array
    {
        return [];
    }

    public function lenses(Request $request): array
    {
        return [];
    }

    public function actions(Request $request): array
    {
        return [];
    }
}
