<?php

namespace App\Nova;

use App\Models\GroupTariff;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\Date;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Image;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Panel;

class GroupTarifsResource extends Resource
{
    public static $model = GroupTariff::class;

    public static $title = 'id';

    public static function label()
    {
        return 'Тарифы салонов'; // TODO: Change the autogenerated stub
    }

    public static $search = [
        'name'
    ];

    public function fields(Request $request): array
    {
        return [
            ID::make()->sortable(),
            Panel::make('Информация', [
                Text::make('Название тарифа', 'name')->required(),
                Number::make('Код на сайте', 'xml_id')->nullable(),
                Date::make('Активен до', 'active_to')->required(),
            ]),

            Panel::make('Связи', [
                BelongsTo::make('Владелец', 'getOwner', User::class)->sortable()->required(),
                BelongsTo::make('Связаная группа', 'getGroup', UserGroupResource::class)->sortable()->required(),

            ]),

            Panel::make('Доп. инфо', [
                Image::make('Подпись', 'sign_path')->disk('public/sign')->nullable(),
            ]),
        ];
    }

    public function cards(Request $request): array
    {
        return [];
    }

    public function filters(Request $request): array
    {
        return [];
    }

    public function lenses(Request $request): array
    {
        return [];
    }

    public function actions(Request $request): array
    {
        return [];
    }
}
