<?php

namespace App\Nova;

use App\Models\UserGroup;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Image;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\Text;

class UserGroupResource extends Resource
{
    public static $model = UserGroup::class;

    public static $title = 'name';

    public static $search = [
        'id', 'name'
    ];

    public static function label()
    {
        return "Пользовательские заведения"; // TODO: Change the autogenerated stub
    }

    public function fields(Request $request): array
    {
        return [
            ID::make()->sortable(),
            Text::make('Название группы/заведения', "name")->sortable()->required(),
            Image::make('Лого', 'logo_path')->disk('public')->nullable(),
            Number::make('Осталось SMS','sms_count')->sortable()->rules('required', 'integer'),
            Number::make('Осталось писем','emails_count')->sortable()->rules('required', 'integer'),
            Number::make('Кол-во пользователей','users_count')->sortable()->rules('required', 'integer'),
            Boolean::make('Может редактировать карточку?','can_edit_card')->sortable()->rules('required', 'integer'),
        ];
    }

    public function cards(Request $request): array
    {
        return [];
    }

    public function filters(Request $request): array
    {
        return [];
    }

    public function lenses(Request $request): array
    {
        return [];
    }

    public function actions(Request $request): array
    {
        return [];
    }
}
